### ISSUE TITLE
Firefox addon source

### ISSUE THREAD

**Issue by tanius** [navi1995/YoutubeWindowedFullScreen#1]
I am using [your Firefox version](https://addons.mozilla.org/en-US/firefox/addon/youtube-window-fullscreen/) that does the same thing as this one does for Chrome. Works a treat! 🙂

When I tried to find the source code for that addon, I only found that the version number (3.1) and release date (2020-07-23) match with this Chrome version. But I could not find a confirmation that indeed this source code is also used to build the Firefox addon, and if so, how I would have to do that.

Could you clarify, maybe in an added `README`? Thank you!

**Comment by navi1995** [comment]
Hi there, sorry for the late response I never seemed to get a notification for this. @tanius There was a certain point in time where I was manually doing Firefox deployments and was not in sync with Chrome deployments. I've since set this up as automated deployments and both will always have the latest code :)
